version: "3.8"

services:
  db:
    image: nouchka/sqlite3
    container_name: sqlite_service
    volumes:
      - ./data:/db
    restart: always
    stdin_open: true
    tty: true
    working_dir: /db

  app:
    build:
      context: ./src
      dockerfile: dockerfile
    container_name: Analyse_des_resultats
    depends_on:
      - db
    volumes:
      - ./data:/db
      - ./src:/app
    environment:
      - DATABASE_PATH=/db
    command: ["python", "/app/main.py"]