services:
  db:
    image: nouchka/sqlite3
    container_name: sqlite_service
    volumes:
      - ./data:/db
    restart: always
    stdin_open: true
    tty: true
    working_dir: /db

  app:
    build:
      context: ./src
      dockerfile: dockerfile
    container_name: Analyseur
    depends_on:
      - db
    ports:
     - "7860:7860"  # Port Gradio
    volumes:
     - ./data:/db
     - ./src:/app
    environment:
     - DATABASE_PATH=/db
    command: >
     bash -c "python /app/main.py && python /app/web_app.py"